// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = TiTleSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * welcome field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.welcome
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	welcome: prismic.KeyTextField;

	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *TiTle → Primary*
 */
export interface TiTleSliceDefaultPrimary {
	/**
	 * Welcome field in *TiTle → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.primary.Welcome
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	Welcome: prismic.KeyTextField;
}

/**
 * Primary content in *TiTle → Items*
 */
export interface TiTleSliceDefaultItem {
	/**
	 * FDND field in *TiTle → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].fdnd
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	fdnd: prismic.KeyTextField;

	/**
	 * Frontender field in *TiTle → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].frontender
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	frontender: prismic.KeyTextField;

	/**
	 * profilepicture field in *TiTle → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].profilepicture
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	profilepicture: prismic.ImageField<never>;

	/**
	 * Name field in *TiTle → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * About field in *TiTle → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].about
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about: prismic.KeyTextField;

	/**
	 * text color field in *TiTle → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].text_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	text_color: prismic.ColorField;

	/**
	 * background color field in *TiTle → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ti_tle.items[].background_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	background_color: prismic.ColorField;
}

/**
 * Default variation for TiTle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TiTleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TiTleSliceDefaultPrimary>,
	Simplify<TiTleSliceDefaultItem>
>;

/**
 * Slice variation for *TiTle*
 */
type TiTleSliceVariation = TiTleSliceDefault;

/**
 * TiTle Shared Slice
 *
 * - **API ID**: `ti_tle`
 * - **Description**: TiTle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TiTleSlice = prismic.SharedSlice<'ti_tle', TiTleSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			TiTleSlice,
			TiTleSliceDefaultPrimary,
			TiTleSliceDefaultItem,
			TiTleSliceVariation,
			TiTleSliceDefault
		};
	}
}
